kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebind-for-deploy
subjects:
  - kind: ServiceAccount
    name: build-bot
    namespace: hongspace
roleRef:
  kind: ClusterRole
  name: role-for-tektondeploy
  apiGroup: rbac.authorization.k8s.io
